[package]
name = "revvy02/replecs-roblox"
description = "Bridges replecs component-driven replication with Roblox Instance references"
version = "0.0.3"
registry = "https://github.com/UpliftGames/wally-index"
realm = "shared"

exclude = ["**"]
include = ["src", "src/**", "wally.toml", "default.project.json", "README.md"]

[dependencies]
jecs = "ukendio/jecs@0.10.4"
replecs = "pepeeltoro41/replecs@0.3.1"
jecs_utils = "pepeeltoro41/jecs-utils@1.4.1"
